# Generated by Django 4.1.4 on 2023-02-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_remove_option_question_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='op1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='op2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='op3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='op4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='no_of_questions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='time_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
